spring:
  application:
    name: zuul-gateway
server:
  port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
zuul:
  routes:
    booking-room-service: /booking/**