spring:
  application:
    name: zuul-gateway

auth-service:
  SECRET_KEY: ZJPisOneBigNoob
  EXPIRE_TIME: 30

server:
  port: 10086

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
zuul:
  routes:
    booking-service: /booking/**
    auth-service: /auth/**
    user-service: /user/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

system:
  filter:
    allowPaths:
      - /auth
      - /user/registry
      - /user/check
      - /booking