spring:
  application:
    name: zuul-gateway
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/meeting_room_reservation_system
#    username: root
#    password: Qianqi971126
#    driver-class-name: com.mysql.cj.jdbc.Driver

#auth-service:
#  SECRET_KEY: ZJPisOneBigNoob
#  EXPIRE_TIME: 30

server:
  port: 10086

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
zuul:
  routes:
    booking-service: /booking/**
    auth-service: /auth/**
    user-service: /user/**
    roomInfo-service: /roomInfo/**
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 2000

system:
  filter:
    allowPaths:
      - /auth
      - /user/registry
      - /user/check
      - /booking
      - /user/activate
      - /roomInfo