spring:
  application:
    name: booking-room-service

  datasource:
    url: jdbc:mysql://localhost:3306/meeting_room_reservation_system
    username: root
    password: Qianqi971126
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9091

eureka:
  instance:
    metadata-map:
      zone: sh2
  client:
    region: sh
    availability-zones:
      sh: sh1,sh2
    service-url:
      sh1: http://localhost:9090/eureka
      sh2: http://localhost:8080/eureka


