spring:
  application:
    name: booking-room

  datasource:
    url: jdbc:mysql://localhost:3306/meeting_room_reservation_system
    username: root
    password: Qianqi971126
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 9091

eureka:
  instance:
    metadata-map:
      zone: sh1
  client:
    region: sh
    availability-zones:
      sh: sh1,sh2
    service-url:
      sh1: http://localhost:9090/eureka
      sh2: http://localhost:8080/eureka
mybatis:
  type-aliases-package: com.jenkins.common
  mapper-locations: classpath*:com/jenkins/common/**/mapper/impl/*Mapper.xml
