spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/meeting_room_reservation_system
    username: root
    password: Qianqi971126
    driver-class-name: com.mysql.cj.jdbc.Driver

auth-service:
  SECRET_KEY: ZJPisOneBigNoob
  EXPIRE_TIME: 30

server:
  port: 9099

eureka:
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

mybatis:
  type-aliases-package: com.jenkins.common
  mapper-locations: classpath*:com/jenkins/common/**/mapper/impl/*Mapper.xml