spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/meeting_room_reservation_system
    username: root
    password: Qianqi971126
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.163.com
    username: noreplyz@163.com
    password: Qianqi971126
    nickname: LittleCuteTest
    default-encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30

mybatis:
  type-aliases-package: com.jenkins.common
  mapper-locations: classpath*:com/jenkins/common/**/mapper/impl/*Mapper.xml


server:
  port: 9091

