spring:
  application:
    name: registry-server
server:
  port: 9090

eureka:
  instance:
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    eureka-connection-idle-timeout-seconds: 10
    fetch-registry: false