spring:
  application:
    name: auth-service

auth-service:
  SECRET_KEY: ZJPisOneBigNoob
  EXPIRE_TIME: 30

server:
  port: 9099

eureka:
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka