spring:
  application:
    name: auth-service
  profiles:
    include: auth-common
#auth-common:
#  SECRET_KEY: ZJPisOneBigIdiot
#  EXPIRE_TIME: 900000

server:
  port: 9099

eureka:
  instance:
    metadata-map:
      zone: sh1
  client:
    region: sh
    availability-zones:
      sh: sh1,sh2
    service-url:
      sh1: http://localhost:9090/eureka
      sh2: http://localhost:8080/eureka
