spring:
  application:
    name: registry-server
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15